### PR TITLE
Manage file branch

### PR DESCRIPTION
**Pull request by riko105**
I'm added some useful git_files in you repo.

### CODE REVIEW

**Comment by riko105** [comment]
But I can't understand - why my previous changes, that I makes in "Add test const and func
" this commit contains again.

**Comment by andrewwoz** [comment]
I don't know. Maybe you make mistake

**Comment by riko105** [comment]
Maybe, OK, soon will deal with this

**Comment by andrewwoz** [comment]
Fix this

**Comment by andrewwoz** [comment]
I have closed this pull request for now. I hope you will fix it

**Pull request closed without merging**
